export const alertConstants = {
  REGISTER_SUCCESS_ALERT: "REGISTER_SUCCESS_ALERT",
  REGISTER_FAIL_ALERT: "REGISTER_SUCCESS_ALERT",

  LOGIN_SUCCESS_ALERT: "LOGIN_SUCCESS_ALERT",
  LOGIN_FAIL_ALERT: "LOGIN_FAIL_ALERT",

  ERROR_ALERT: "ALERT_ERROR",
  CLEAR_ALERT: "ALERT_CLEAR",
  SET_ALERT: "SET_ALERT",
};

export default alertConstants;
