const authConstants = {
  SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "USER_SIGNUP_FAILURE",

  SIGNIN_REQUEST: "USER_SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "USER_SIGNIN_FAILURE",

  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USER_LOGOUT",

  USER_LOADED: "USER_LOADED",

  AUTH_ERROR: "AUTH_ERROR",

  CHANGE_PASSWORD_SUCCESS: "USER_PASSWORD_CHANGE_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "USER_PASSWORD_CHANGE_FAILURE",
  CHANGE_EMAIL_SUCCESS: "USER_EMAIL_CHANGE_SUCCESS",
  CHANGE_EMAIL_FAILURE: "USER_EMAIL_CHANGE_FAILURE",

  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWROD",

  SET_BACK_LOADING: "SET_BACK_LOADING",

  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  CHANGE_ACTIVE_STATUS: "CHANGE_ACTIVE_STATUS",
  EDIT_USER: "EDIT_USER",
};

export default authConstants;
