const authConstants = {
  SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "USER_SIGNUP_FAILURE",

  SIGNIN_REQUEST: "USER_SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "USER_SIGNIN_FAILURE",

  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USER_LOGOUT",

  USER_LOADED: "USER_LOADED",

  AUTH_ERROR: "AUTH_ERROR",
};

export default authConstants;
