const chatConstants = {
  GET_CHAT: "GET_CHAT",
  AFTER_POST_MESSAGE: "AFTER_POST_MESSAGE",
  CHAT_ERROR: "CHAT_ERROR",
  SET_CURR_ACTIVE_CHAT: "SET_CURR_ACTIVE_CHAT",
  ADD_CHAT_ITEM: "ADD_CHAT_ITEM",
  RENDER_CHAT: "RENDER_CHAT",
};

export default chatConstants;
