const profileConstants = {
  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  PROFILE_ERROR: "PROFILE_ERROR",
  CLEAR_PROFILE: "ClEAR_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",

  ADD_USER: "ADD_USER",
  ADD_USER_ERROR: "ADD_USER_ERROR",
};

export default profileConstants;
