const profileConstants = {
  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  PROFILE_ERROR: "PROFILE_ERROR",
  CLEAR_PROFILE: "ClEAR_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",

  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  CHANGE_ACTIVE_STATUS: "CHANGE_ACTIVE_STATUS",
  EDIT_USER: "EDIT_USER",
};

export default profileConstants;
