const profileConstants = {
  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  PROFILE_ERROR: "PROFILE_ERROR",
  CLEAR_PROFILE: "ClEAR_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
};

export default profileConstants;
