const searchConstants = {
  SEARCH_REQUEST: "SEARCH_REQUEST",
  SEARCH_ERROR: "SEARCH_ERROR",
  REORDER_SEARCH: "REORDER_SEARCH",
  CLEAR_SEARCH: "CLEAR_SEARCH",
  LOAD_ROUTE: "LOAD_ROUTE",
  LOAD_DIRECTION_STEPS: "LOAD_DIRECTION_STEPS",
  UPDATE_DIRECTION_STEPS: "UPDATE_DIRECTION_STEPS",
  UPDATE_USER_LOCATION: "UPDATE_USER_LOCATION",
  SET_TRAVEL_MODE: "SET_TRAVEL_MODE",
  SET_RENDER_ROUTE: "SET_RENDER_ROUTE",
  SET_RENDER_LOCATION: "SET_RENDER_LOCATION",
};

export default searchConstants;
