const searchConstants = {
  SEARCH_REQUEST: "SEARCH_REQUEST",
  SEARCH_ERROR: "SEARCH_ERROR",
  REORDER_SEARCH: "REORDER_SEARCH",
  CLEAR_SEARCH: "CLEAR_SEARCH",
  LOAD_ROUTE: "LOAD_ROUTE",
  LOAD_DIRECTION_STEPS: "LOAD_DIRECTION_STEPS",
  UPDATE_DIRECTION_STEPS: "UPDATE_DIRECTION_STEPS",
  UPDATE_USER_LOCATION: "UPDATE_USER_LOCATION",
};

export default searchConstants;
