const userConstants = {
  CHANGE_PASSWORD_REQUEST: "USER_PASSWORD_CHANGE_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "USER_PASSWORD_CHANGE_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "USER_PASSWORD_CHANGE_FAILURE",

  CHANGE_EMAIL_REQUEST: "USER_EMAIL_CHANGE_REQUEST",
  CHANGE_EMAIL_SUCCESS: "USER_EMAIL_CHANGE_SUCCESS",
  CHANGE_EMAIL_FAILURE: "USER_EMAIL_CHANGE_FAILURE",
};

export default userConstants;
