const userConstants = {
  SIGNUP_REQUEST: "USERS_SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "USERS_SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "USERS_SIGNUP_FAILURE",

  SIGNIN_REQUEST: "USERS_SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "USERS_SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "USERS_SIGNIN_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  LOGOUT: "USERS_LOGOUT",
};

export default userConstants;
